{% set name = "pycountry" %}
{% set version = "18.12.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ec4020b2b15cd410893d573820d42ee12fe50365332e58c0975c953b60a16de

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pycountry

about:
  home: https://pypi.org/project/pycountry/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'pycountry provides the ISO databases for the standards' 
  description: |
    The package includes a copy from Debian’s pkg-isocodes and makes the 
    data accessible through a Python API.
    Translation files for the various strings are included as well.
  doc_url: https://pypi.org/project/pycountry/
  dev_url: https://bitbucket.org/flyingcircus/pycountry/

extra:
  recipe-maintainers:
    - CurtLH
