{% set name = "pycountry" %}
{% set version = "22.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2163a246c585894d808f18783e19137cb70a0c18fb36748dc01fc6f109c1646

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pycountry

about:
  home: https://pypi.org/project/pycountry/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: pycountry provides the ISO databases for the standards
  description: |
    The package includes a copy from Debian’s pkg-isocodes and makes the 
    data accessible through a Python API.
    Translation files for the various strings are included as well.
  doc_url: https://pypi.org/project/pycountry/
  dev_url: https://bitbucket.org/flyingcircus/pycountry/

extra:
  recipe-maintainers:
    - CurtLH
