travis:
  secure:
    BINSTAR_TOKEN: AUjmY581BYTFzCgZGFaV8wY/10szwK9OVwa+JjcwKqLAB7Ng9a8mNs/KXpjwpgAuK9uCZdpJ+EeSWApZe2bt9nb/W8ELgTFDWa+zTH+B8WT++Lm1qGFFhFCQCLO8MrotjW9/It0ceUb8vondiBlWGz6ufBriYecETtPIjaFWGEObroqSiWiCoMI3Qo0ykHGXs3fIAkPGX31iu826I3oBwaFk/Jd9msJFW6ALPhmXisxOiZuVAuwaP/x2pp+hCIdwxrP4NBthtGF8CQqbA/vkFRcOx5BWV5/cZRx/nNkMzdyGU5q2hfTU337Qq+AkGPYResaHSoAuSaaSxDlqfny8P+IYXw2NLJKU7zLU4YGZ/S0bDCZpNNCj7LIObr/6C3TfFDN0D1TQ3KDcr3jzaG/D5022VjgVLuf7utJXSDrmuLXrBYgXvmrvDRdg+NfmdMZNMDyCdOOCPkUfaWzwNWiWMgqjBuRL0YEHVpKQvS7Fnzui97+d0fZqX28Sk0KS32/UY4a6lfT30HrBcc7WBoLzHcvRbDKyQ4tF6qMVn5h+MmHFCnXLVTAbUhc4uDM6tDP1PnvXy1yIvxTpkH6WqrjwFq1goPisjQurh13zQBt0aIdlz1fF6J6I9rLhBppS1Uxl004V/3fXSta6DeAsAlyZ8jf84c+zeuAbBmFWWMaATDY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
