travis:
  secure:
    BINSTAR_TOKEN: f2gYveJ2mW5BMz4jAWHugs/qCjc/YfoCG1XQnUZew17dX9K8FOMo/106VQT7CQdE0DfEVLJBXPjCIaGLLZaDOJXwudmP9fkOxR0cPrNscNEmICLctRmPaaatPCHYSoIiJUgM8sUTqekE7nI1aTWYlP7wfb8BU/66ISh5J6g2t6QRhDDziTPji4CDL9+haF0iZ2lcXu9qryNoLe/xWMy8sJfv0GejYF2GTCuuuNM3wrgh9UyqE1yeaDdM95o5E992wHc1/HC7kBLdhdS6xRGFmSFpE9oHWdF0NyKjMHa9Al5vbBOnmuHcAs7qY30RnUOVketT+LYuzosRLRlthUQR2iAV37yWMgA88yWZFRDO8fllF6vrZpVlHTI6v6/k5QqiskgMT1XfVy7ZtamQmnhFDaj0ZJAkuG1jh1TKdHLGaIn/0DjMQ9rJTtDmt5jctLQ+3UaOoKs6t11VajJ/yDYNFapAvo5AHE0B0rPicA3/HDrBGiR/aiGJ+MmkAq7Ea5l5O8POXvyuGnMZkwwNtS1+1TAGgmKs3W4JSSjoklqHI7gM+UOZTx/+YqtEMB8huWHPiIOEKXTDUXHPKon87jgoQd7tP/lU8JdsxNIY6osezUxrrRDvZwAjDB6U5Yk7JtuK9jXb9dGiJ7RO2xplTcRYIfnxfb2MyVJYq9vDZBk/72w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
